//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartPresenter.UI.Controls.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LibraryTabResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LibraryTabResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartPresenter.UI.Controls.Resources.LibraryTabResources", typeof(LibraryTabResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Library Folder.
        /// </summary>
        public static string Add_Library_Folder {
            get {
                return ResourceManager.GetString("Add_Library_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Location.
        /// </summary>
        public static string Change_Library_Folder_Location {
            get {
                return ResourceManager.GetString("Change_Library_Folder_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Library.
        /// </summary>
        public static string Context_Menu_Header_Add_Library {
            get {
                return ResourceManager.GetString("Context_Menu_Header_Add_Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Playlist.
        /// </summary>
        public static string Context_Menu_Header_Add_Playlist {
            get {
                return ResourceManager.GetString("Context_Menu_Header_Add_Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Playlist Group.
        /// </summary>
        public static string Context_Menu_Header_Add_Playlist_Group {
            get {
                return ResourceManager.GetString("Context_Menu_Header_Add_Playlist_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Presentation.
        /// </summary>
        public static string Context_Menu_Header_Add_Presentation {
            get {
                return ResourceManager.GetString("Context_Menu_Header_Add_Presentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Document_List_Category_Column_Header {
            get {
                return ResourceManager.GetString("Document_List_Category_Column_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Document_List_Name_Column_Header {
            get {
                return ResourceManager.GetString("Document_List_Name_Column_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Document_List_Size_Column_Header {
            get {
                return ResourceManager.GetString("Document_List_Size_Column_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Documents_Header {
            get {
                return ResourceManager.GetString("Documents_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string Library_Tab_Header {
            get {
                return ResourceManager.GetString("Library_Tab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File Location.
        /// </summary>
        public static string Open_File_Location {
            get {
                return ResourceManager.GetString("Open_File_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline.
        /// </summary>
        public static string Outline_Tab_Header {
            get {
                return ResourceManager.GetString("Outline_Tab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        public static string Playlists_Header {
            get {
                return ResourceManager.GetString("Playlists_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Library Folder.
        /// </summary>
        public static string Remove_Library_Folder {
            get {
                return ResourceManager.GetString("Remove_Library_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize.
        /// </summary>
        public static string Resize {
            get {
                return ResourceManager.GetString("Resize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slides.
        /// </summary>
        public static string Slides_Tab_Header {
            get {
                return ResourceManager.GetString("Slides_Tab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
    }
}
