//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartPresenter.Service.MediaManagement.Test.MediaManagementServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MediaManagementServiceReference.IMediaManagementService")]
    public interface IMediaManagementService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMediaManagementService/GetAllMediaFiles", ReplyAction="http://tempuri.org/IMediaManagementService/GetAllMediaFilesResponse")]
        string[] GetAllMediaFiles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMediaManagementService/GetAllMediaFiles", ReplyAction="http://tempuri.org/IMediaManagementService/GetAllMediaFilesResponse")]
        System.Threading.Tasks.Task<string[]> GetAllMediaFilesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMediaManagementServiceChannel : SmartPresenter.Service.MediaManagement.Test.MediaManagementServiceReference.IMediaManagementService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MediaManagementServiceClient : System.ServiceModel.ClientBase<SmartPresenter.Service.MediaManagement.Test.MediaManagementServiceReference.IMediaManagementService>, SmartPresenter.Service.MediaManagement.Test.MediaManagementServiceReference.IMediaManagementService {
        
        public MediaManagementServiceClient() {
        }
        
        public MediaManagementServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MediaManagementServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MediaManagementServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MediaManagementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetAllMediaFiles() {
            return base.Channel.GetAllMediaFiles();
        }
        
        public System.Threading.Tasks.Task<string[]> GetAllMediaFilesAsync() {
            return base.Channel.GetAllMediaFilesAsync();
        }
    }
}
